DEBUG 2023-04-20 15:41:24.618 UTC: 	 CRAB Client version: v3.230404
DEBUG 2023-04-20 15:41:24.618 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-04-20 15:41:24.618 UTC: 	 Executing command: 'submit'
DEBUG 2023-04-20 15:41:24.618 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2023-04-20 15:41:24.634 UTC: 	 Will use CRAB configuration file crab_StreamExpress_Run2023A-v1.py
DEBUG 2023-04-20 15:41:24.635 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-04-20 15:41:24.642 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-04-20 15:41:24.643 UTC: 	 Working area '/work/pbaertsc/pixel/CMSSW_13_0_0/src/SiPixelTools/PixelTriplets/tasks/crab_StreamExpress_Run2023A-SiPixelCalSingleMuonTight-Express-v1' already exists 
Please change the requestName in the config file
ERROR 2023-04-20 15:41:24.643 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/work/pbaertsc/pixel/CMSSW_13_0_0/src/SiPixelTools/PixelTriplets/tasks/crab_StreamExpress_Run2023A-SiPixelCalSingleMuonTight-Express-v1' already exists 
Please change the requestName in the config file
INFO 2023-04-20 15:41:24.647 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_0/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-04-21 13:53:45.922 UTC: 	 CRAB Client version: v3.230404
DEBUG 2023-04-21 13:53:45.923 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-04-21 13:53:45.923 UTC: 	 Executing command: 'submit'
DEBUG 2023-04-21 13:53:45.923 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2023-04-21 13:53:45.939 UTC: 	 Will use CRAB configuration file crab_StreamExpress_Run2023A-v1.py
DEBUG 2023-04-21 13:53:45.940 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-04-21 13:53:45.947 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-04-21 13:53:45.947 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2023-04-21 13:53:45.947 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/ClientUtilities.py", line 381, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230404.00/lib/CRABClient/ClientUtilities.py", line 359, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2023-04-21 13:53:45.951 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_0/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-05-22 15:00:20.377 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-22 15:00:20.377 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-05-22 15:00:20.377 UTC: 	 Executing command: 'submit'
DEBUG 2023-05-22 15:00:20.378 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2023-05-22 15:00:20.396 UTC: 	 Will use CRAB configuration file crab_Muon_Run2023C-v2.py
DEBUG 2023-05-22 15:00:20.396 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-05-22 15:00:20.405 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-05-22 15:00:20.406 UTC: 	 Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v2' already exists 
Please change the requestName in the config file
ERROR 2023-05-22 15:00:20.406 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v2' already exists 
Please change the requestName in the config file
INFO 2023-05-22 15:00:20.410 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-06-08 07:24:41.166 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-08 07:24:41.166 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-06-08 07:24:41.166 UTC: 	 Executing command: 'status'
DEBUG 2023-06-08 07:24:41.167 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
ERROR 2023-06-08 07:24:41.168 UTC: 	 Error: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
ERROR 2023-06-08 07:24:41.168 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
INFO 2023-06-08 07:24:41.170 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-06-08 08:47:39.296 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-08 08:47:39.296 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-06-08 08:47:39.296 UTC: 	 Executing command: 'status'
DEBUG 2023-06-08 08:47:39.297 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
ERROR 2023-06-08 08:47:39.298 UTC: 	 Error: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
ERROR 2023-06-08 08:47:39.298 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
INFO 2023-06-08 08:47:39.300 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-06-08 08:47:48.897 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-08 08:47:48.897 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-06-08 08:47:48.898 UTC: 	 Executing command: 'status'
DEBUG 2023-06-08 08:47:48.898 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
ERROR 2023-06-08 08:47:48.899 UTC: 	 Error: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
ERROR 2023-06-08 08:47:48.900 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4/ is not a valid CRAB project directory.
INFO 2023-06-08 08:47:48.903 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2023-06-28 13:39:51.037 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-28 13:39:51.037 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2023-06-28 13:39:51.037 UTC: 	 Executing command: 'submit'
DEBUG 2023-06-28 13:39:51.037 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2023-06-28 13:39:51.039 UTC: 	 Will use CRAB configuration file crab_Muon_Run2023C-v4.py
DEBUG 2023-06-28 13:39:51.039 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-06-28 13:39:51.041 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-06-28 13:39:51.042 UTC: 	 Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4' already exists 
Please change the requestName in the config file
ERROR 2023-06-28 13:39:51.042 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2023C-SiPixelCalSingleMuonTight-PromptReco-v4' already exists 
Please change the requestName in the config file
INFO 2023-06-28 13:39:51.045 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2024-01-15 11:18:23.241 UTC: 	 CRAB Client version: v3.231101
DEBUG 2024-01-15 11:18:23.241 UTC: 	 Running on: Linux t3ui03.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2024-01-15 11:18:23.241 UTC: 	 Executing command: 'submit'
DEBUG 2024-01-15 11:18:23.242 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2024-01-15 11:18:23.244 UTC: 	 Will use CRAB configuration file crab_Muon_Run2023D.py
DEBUG 2024-01-15 11:18:23.244 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-01-15 11:18:23.247 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2024-01-15 11:18:23.248 UTC: 	 Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_PixelTriplets_2023D_370776' already exists 
Please change the requestName in the config file
ERROR 2024-01-15 11:18:23.248 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231101.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231101.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231101.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231101.00/lib/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231101.00/lib/CRABClient/ClientUtilities.py", line 390, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/tasks/crab_PixelTriplets_2023D_370776' already exists 
Please change the requestName in the config file
INFO 2024-01-15 11:18:23.252 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_13_0_6/src/SiPixelTools/PixelTriplets/crab.log
DEBUG 2024-04-24 11:16:44.816 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-04-24 11:16:44.817 UTC: 	 Running on: Linux t3ui02.psi.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux Server 7.9 (Maipo)
DEBUG 2024-04-24 11:16:44.817 UTC: 	 Executing command: 'submit'
DEBUG 2024-04-24 11:16:44.818 UTC: 	 Found CRAB cache file /t3home/pbaertsc/.crab3
INFO 2024-04-24 11:16:44.846 UTC: 	 Will use CRAB configuration file crab_Muon_Run2024A.py
DEBUG 2024-04-24 11:16:44.846 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-04-24 11:16:44.854 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-04-24 11:16:44.855 UTC: 	 Working area '/work/pbaertsc/pixel/CMSSW_14_0_4/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2024A-SiPixelCalSingleMuonTight-PromptReco-v1' already exists 
Please change the requestName in the config file
ERROR 2024-04-24 11:16:44.855 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/work/pbaertsc/pixel/CMSSW_14_0_4/src/SiPixelTools/PixelTriplets/tasks/crab_Muon0_Run2024A-SiPixelCalSingleMuonTight-PromptReco-v1' already exists 
Please change the requestName in the config file
INFO 2024-04-24 11:16:44.859 UTC: 	 Log file is /work/pbaertsc/pixel/CMSSW_14_0_4/src/SiPixelTools/PixelTriplets/crab.log
